name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install and Build Backend
      run: |
        cd server
        npm install
        echo "✅ Backend dependencies installed"
    
    - name: Install and Build Frontend
      run: |
        cd client
        npm install
        npm run build
        echo "✅ Frontend built successfully"
    
    - name: Test Docker Build Backend
      run: |
        cd server
        docker build -t test-backend .
        echo "✅ Backend Docker build successful"
    
    - name: Test Docker Build Frontend
      run: |
        cd client
        docker build -t test-frontend .
        echo "✅ Frontend Docker build successful"
    
    - name: Success
      run: echo "🚀 All builds completed successfully!"