name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install and Build Backend
      run: |
        cd server
        npm install
        echo "✅ Backend dependencies installed"
    
    - name: Install and Build Frontend
      run: |
        cd client
        npm install
        npm run build
        echo "✅ Frontend built successfully"
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/skillbridge-backend:latest
    
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/skillbridge-frontend:latest
    
    - name: Success
      run: |
        echo "🚀 Deployment completed!"
        echo "Backend: ${{ secrets.DOCKER_USERNAME }}/skillbridge-backend:latest"
        echo "Frontend: ${{ secrets.DOCKER_USERNAME }}/skillbridge-frontend:latest"